[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","UP","B"]
ignore = ["E203","E501"]

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "-q"
